### PR TITLE
Use `@xai_component` to specify which components should be exposed in UI

### PR DESCRIPTION
**Pull request by treo**
# Description

This adds the ADR on using a decorator to specify what components should be available, and implements those changes.

## Pull Request Type

- [X] Xpipes Core (Jupyterlab Related changes)
- [ ] Xpipes Canvas (Custom RD Related changes)
- [X] Xpipes Component Library
- [X] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Tests

1. Components List
    1. Start Jupyter Lab
    2. Switch to component list
    3. Assert that all expected components are available

2. Specifying Component Colors (precondition: Jupyter Lab already running)
   1. Switch to component list
   2. Add / Change `color=` keyword on `@xai_component` decorator for the chosen component
   3. Click reload to see border color change of component

## Tested on?

- [X] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )

### CODE REVIEW

**Comment by AdrySky** [comment]
Thanks for this feature as now I can expose which component I wanted rather than only components that 'extends Component class' are available. 

I've tested out the decorator and I can confirm that it can:

1. Expose the component to the parser
2. Set the color of the component

However, I'm unable to run the xpipes as it'll give this error :
decorator

Although, if I remove the `(color= foo)` keyword on the decorator from `@xai_component(color="blue")` to `@xai_component`, I can run the xpipes successfully

**Comment by treo** [comment]
Good catch. I forgot that python is a little weird in the handling of the two different decorator forms. 

Fixed it and tested it by connecting the HelloComponent and the HyperParameterHelloComponent (one with additional decorator parameter, one without) and both work for me.

**Comment by AdrySky** [comment]
Tested. Both working perfectly. I also added a missing xai_component import. Looks good to me. 

Though, I'll let Fahreza do the merging and one last check incase I missed anything. Thanks Paul.

**Comment by treo** [comment]
One more note:

The way it is implemented, the `@xai_component` decorator will put whatever is put there as a keyword into the component definition. 

That means that if you for example want to specify anything about it like `path`,`task` (name of the component), `rootFile` (group name in UI), `type` , you can just put them there and it will override what ever was automatically extracted.

That can also be used to add things like custom html, it only needs to be accepted by the UI.

**Comment by AdrySky** [comment]
Interesting. I've tested few of them and here what I found.

1. `path`

-  I can change its path.  Though, I need to add another 3 char string to the path like this. 
path
- Somehow, the codegen delete the last 3 char string. Need to check on that if we want to use this. 
- I only tested for the same file path. 
- Not sure what the use case for this yet.

2. `task`

- I can change the component name from the UI and codegen perspective. 
- However, the codegen currently will look for the component's name from the UI to `import`. Using this feature, it'll look for the new named component which doesn't exist. So I don't think we can use this feature yet. 
- As long we can figure out a way for the codegen to capture the data internally rather than from the UI, only then we can use this.

3. `rootFile`

- I can change its group name. Though, it need the folder and its `__init__.py` to exist for the parser to allow the new component to exist in that group. It's also case-sensitive(uppercase needed).
- From Mr. Eduardo, he said he prefer 'Category' rather than 'rootFile'.

4. `type`

- I'm not sure how to test this yet.

5. `variables`

- I'm not sure how to type this one yet.

**Comment by treo** [comment]
I agree with you on those things. 

There isn't really much use for them yet. They just happen to exist in that way, because the implementation passes on all keywords specified on the decorator into the object that is returned to the UI. 

We can change the design to not override anything, but I think it somewhat makes sense to allow it to override defaults. 

With this in mind, we can probably reduce some of the tight coupling in the code generator rework.

**Review by MFA-X-AI — COMMENTED** [review]
Thanks for the pull request! 

1. The ADR is definitely good to have, looking forward to using that to track our future big feature implementations and changes. 

2. I've tested the decorator function by removing and adding it to the component classes. Component appears and disappears in the Tray Widget as expected. Tested in windows and linux. 

3. I've tested the color change feature. Doesn't seem to break any existing examples either. Will add this to the documentation changes. Tested in windows and linux. 

4. I've noted the groundwork for path, task, rootFile, type, and variable. I think these can be features to be properly implemented in the future, especially the rootFile/Category one.

As I'm writing this, I guess it would be good to have a review template as well... I guess just need to change the rootFile -> Category and we can merge this thread. Will do that now.

**Pull request merged**
