### PR TITLE
Refactor python parsing and variable handling

### PR DESCRIPTION
**Pull request by treo**
The filbert.js based python parser produced a very bad parse tree,
which required a very brittle interpreter to make any use of it.
It therefore broke often in unexpected ways.

As we have a server extension now, we can use the python "ast" module
to parse and unparse the code exactly as well as the actual python
parser can.

The string-based variable handling from before the change is brittle and error-prone.

This uses a rich representation for every variable, which makes the additional parsing step unnecessary.

I've tested the changes manually with some spot-checks and as far as I can tell everything still works as expected. This includes running a simple xpipes file.

But maybe there are things that implicitly depend on something I've changed where I didn't notice something breaking. 

I've left a few TODO comments which I'd like to discuss, before we merge this.

### CODE REVIEW

**Comment by AdrySky** [comment]
Thanks @treo for the pull request. The refactored python parser working great. I can still drag and drop components to canvas. However, there a few things I noticed while reviewing.

1. There a duplicate of components in all folder except the 'General'
2. It also parsed `.ipynb_checkpoints `. When you edit a python script, it'll create a checkpoint folder. The python parser will also parse that folder. I assume this is related to parsing a folder beside "xai-" prefix.
3. Changing the config file doesn't affect the component library. Even if I delete/change the base path, the component library still working fine.

**Review by MFA-X-AI — COMMENTED** [review]
That was blazing fast! Thanks Paul. The python parser core functionalities looks to be working well from finding the components, dragging them in and running the components. Debugger looks perfectly fine too. I've also taken notice on your refactoring on our xpipes bodywidget, that is very much appreciated. :) 

In regards to the bugs, I've noted a few:

1) I've noticed that the new parser can parse even folders inside folders. While it's really cool from the user perspective, I would feel like it's dangerous especially when we implement custom folder search, the user choses say their home dir as their base. Would need to discuss again whether keeping it unlimited is a good thing or not.

2) I've also noticed that while it parses anywhere, it also parses _**everything**_, even the .ipynb checkpoints folders. Might want to exclude that.  

3) I've noticed a strange behavior in the tray widget where every component is duplicated. I thought it was duplicated because of said .ipynb checkpoints, but after deleting it there is at least another copy of the same component. 

I think that's it from my run through, will review it again after the duplication bug is fixed.

**Review by MFA-X-AI — APPROVED** [review]
That was great, components are now not duplicated, and I've even noticed that for the component tray widget, it will automatically update it on save. IE:

**Previous:**
When user changes the python xai component, saves it, and drags into the canvas, the component rendered will be the old one.  The user would have to press the refresh button to update it.

**Now:** 
By simply saving the python file, it would correctly render the updated component on drop.

Amazing!

I can also semi-alter the the python parser BASE_DIR from the config.ini... which leads to a problem of it not being able to update the parsed dir unless we restart the jupyterlab. So basically if we specify a different folder aside from what's expected, Xpipes tray widget will render the components in the tray correctly, but will not be able to do other functions like opening the component by clicking on it in the tray widget or running it.

How to reproduce it:

1. move xai_components to a different dir
2. change the xai_components BASE_PATH in  .xpipes/config.ini to said dir
3. Boot jupyterlab. The tray widget will correctly render the components but that's all.

The use case for this is considering a certain very polished ML computing environment, restarting the jupyterlab would mean terminating the jupyterlab session and starting it over again. Ideally Xpipes should be able reload the config by pressing refresh.

That said I think this might be a different pull request altogether to consider the config handling, since this pull request already does a lot.

**Review by AdrySky — APPROVED** [review]
There is no more duplicate of components. Personally, the folders having the prefix "xai-" that only can be parsed is better since it kind of narrow down which folder has the components. 

Regarding the config file, I just noticed we can see the changes when we relaunched jupyterlab.

Also, you're right about remove remapping and only use compatible type name. It'll refactored most of our code and put all components part in one place. Probably in the later feature.

Thanks again Paul for the changes.

**Pull request merged**
