### PR TITLE
Dataset from dir support

### PR DESCRIPTION
**Pull request by MFA-X-AI**
1. Added dataset reading from directory support to `xai_learning/training.py`. Uses skikitlearn LabelEncoder to convert folder names into labels, and cv2 to read the image.
2. Added opencv-python to  `xai_learning/requirements.txt`

**Test:**

1. Make an image dataset with the folder name as the class name and populate with images. Alternatively try this weather dataset from kaggle: https://www.kaggle.com/vijaygiitk/multiclass-weather-dataset
2. Open KerasTrainImageClassifier.xpipe
3. Supply the path to the ReadDataSet Component as a `literal string`, eg I downloaded the weather dataset and placed inside   `/Datasets/dataset/`
4. Run the xpipe. You should be able to train the model.

### CODE REVIEW

**Comment by quietrex** [comment]
Tested ok, but I would prefer using path join to merge the path before doing os.listdir. As It will show error if I put "Datasets/dataset" instead

**Comment by MFA-X-AI** [comment]
Thanks for the suggestion @quietrex , I've improved the path handing, error output, and also added a progress bar for the image loading. It looks like this now. 

```
Executing: ReadDataSet
Detecting 6 classes in Datasets/dataset.
 50%|████████████████████████████████████████▌                                        | 3/6 [00:02<00:03,  1.19s/it]
Error reading file: C:\Users\Fahreza\Documents\GitHub\xpipes2\xpipes\Datasets\dataset\rainy\rain141.jpg. Skipping...
 67%|██████████████████████████████████████████████████████                           | 4/6 [00:05<00:03,  1.84s/it]
Error reading file: C:\Users\Fahreza\Documents\GitHub\xpipes2\xpipes\Datasets\dataset\shine\shine131.jpg. Skipping...
100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:09<00:00,  1.54s/it]
```

**Comment by quietrex** [comment]
> Thanks for the suggestion @quietrex , I've improved the path handing, error output, and also added a progress bar for the image loading. It looks like this now.
> 
> ```
> Executing: ReadDataSet
> Detecting 6 classes in Datasets/dataset.
>  50%|████████████████████████████████████████▌                                        | 3/6 [00:02<00:03,  1.19s/it]
> Error reading file: C:\Users\Fahreza\Documents\GitHub\xpipes2\xpipes\Datasets\dataset\rainy\rain141.jpg. Skipping...
>  67%|██████████████████████████████████████████████████████                           | 4/6 [00:05<00:03,  1.84s/it]
> Error reading file: C:\Users\Fahreza\Documents\GitHub\xpipes2\xpipes\Datasets\dataset\shine\shine131.jpg. Skipping...
> 100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:09<00:00,  1.54s/it]
> ```

Thanks for modifying the logic. It works great as it is. Nice work!

**Review by quietrex — APPROVED** [review]
It works fine!

**Pull request merged**
