### PR TITLE
✨Change into Document Widget context to enable 'dirty' state

### PR DESCRIPTION
**Pull request by AdrySky**
Change the context from Document Model into **Document Widget**. This will allow JupyterLab to detect the changes in the context which leads to any **changed but unsaved** xpipes will display its '**dirty**' state(which can be seen from the close button change from '**X**' icon to **filled circle** icon).

This changes also include changing back using the **Application** as the previous method doesn't bode well with changing to Document Widget.

Also, add save function when creating new xpipes so that the context exist.

Since JupyterLab can detect the context changes, we can use Jupyterlab's feature like save, reload, revert and etc. Thus, indirectly fix the save, revert and reload bugs. Also, the reload and revert signal was removed.

In addition, remove some unused codes and clean up some of the imports.

Currently, there a few ways for JupyterLab to **detect** the changes in xpipes which are:

1. Nodes dropped and deleted
2. New link connect to nodes
3. New or unconnected link being deleted

Some known changes which JupyterLab **doesn't detect** :

1. Moving the nodes
2. Delete an already connected links

### CODE REVIEW

**Review by MFA-X-AI — COMMENTED** [review]
Seems like there's a few things missing in the build setup. Here's a gist:

https://gist.github.com/MFA-X-AI/6678a011666f662de6f8da6e7c7f8ec7

To test out your own build, you can try cloning a clean xpipes and switching to this branch. Looking forward to see this work!

**Comment by AdrySky** [comment]
Yeah, my bad on that. Somehow I accidently delete that line and didn't notice the error while doing commit. Already fix the change. It'd be great if you could check it again. Thanks

**Review by MFA-X-AI — COMMENTED** [review]
Thanks! It compiles correctly this time, I've tested these functions:
Save Xpipe
Reload Xpipe
Revert Xpipe
And it looks like it's functioning okay. The revert not working for node movement is a bit jarring, but nothing gamebreaking. The run button seems to be a bit buggy. To reproduce:

1) Link a simple diagram
2) Save it
3) Alt-tab and tab back
4) You need to press Run trice for it to run, with the first 2 presses giving:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getNode')
    at getTargetNodeModelId (xpipeBodyWidget.js:162)
    at getAllNodesFromStartToFinish (xpipeBodyWidget.js:197)
    at checkAllCompulsoryInPortsConnected (xpipeBodyWidget.js:495)
    at saveAndCompileAndRun (xpipeBodyWidget.js:552)
    at handleRunClick (xpipeBodyWidget.js:601)
    at handleRunSignal (xpipeBodyWidget.js:1100)
    at m (jlab_core.e435464f77ebcadba581.js?v=e435464f77ebcadba581:2)
    at Object.l [as emit] (jlab_core.e435464f77ebcadba581.js?v=e435464f77ebcadba581:2)
    at e.emit (jlab_core.e435464f77ebcadba581.js?v=e435464f77ebcadba581:2)
    at execute (index.js:207)
```

It has to do with the darn alt tab error. Do you think you can look into this?

**Comment by MFA-X-AI** [comment]
Ah okay. After more testing it looks like it's not the alt-tab bug, but it's rather when we make changes and directly press run, it would trigger the dirty state, and only by pressing thrice it saves and compiles it. Something like this:

tripleclick

I think we should revert the run logic back so that if the xpipes is unsaved, it will prompt the user to save first. The current Xpipes would force the users to overwrite their previous config. In the future we can then reenable the express run.

**Comment by AdrySky** [comment]
I fixed the run bug while in `dirty` state. I make sure it save first when running the dialog. We can still use the express run.

**Comment by AdrySky** [comment]
Just notice another bug. The hyperparameter still there in the run dialog even when the node is already deleted.
run dialog hyper

Though, entering a new HelloHyperparameter fix it but not what we wanted.

**Comment by MFA-X-AI** [comment]
Interesting. I think it has to do with the getActiveDiagram() not updating. In the old way, this was avoided by re-rendering everything at changes (which was a poor way of doing it).

**Comment by AdrySky** [comment]
Just notice the hyperparameter node doesn't need to link to any node for its to show in the run dialog. You can try it in master. However, the display bug only happen in this branch.

**Comment by MFA-X-AI** [comment]
> Just notice the hyperparameter node doesn't need to link to any node for its to show in the run dialog. 

Yeah this one is by design. The only ones considered in the codegens are components, literals are free from it.

**Comment by AdrySky** [comment]
So I fixed the 'deleted hyperparameter's input still persist' bug. However, it can still be reproduce if running while in dirty state as the `initialize` state is not set yet. Meaning, user need to click save before running if the document is 'dirty'. 

So what do you think @MFA-X-AI , should we prompt user to make sure the xpipes is clean(saved) before running it?

**Comment by MFA-X-AI** [comment]
Yep, sounds like something we want since we want to warn users that their Xpipes will be overwritten if run. In the next pull request we can make an express run function.

**Review by MFA-X-AI — APPROVED** [review]
Works perfectly! Can confirm these functions work:
1) When these 3 events happen:
a. Nodes dropped and deleted
b. New link connect to nodes
c. New or unconnected link being deleted
 Xpipes goes into a dirty state
2) Run button will prompt user to save and run if in dirty state
3) Bug free and smooth!

Thanks for the good work!

**Pull request merged**
